name: Lint

on: pull_request

jobs:
  code:
    name: Lint code
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        working-directory: backend

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
        working-directory: backend

      - name: Install dependencies
        working-directory: backend  
        uses: bahmutov/npm-install@v1
        
      - name: Run ESLint
        run: yarn lint
        working-directory: backend
